export const types = Object.freeze({
    FILTER_SET_CLOUDY: 'FILTER_SET_CLOUDY',
    FILTER_SET_SUNNY: 'FILTER_SET_SUNNY',
    FILTER_SET_MIN_TEMP: 'FILTER_SET_MIN_TEMP',
    FILTER_SET_MAX_TEMP: 'FILTER_SET_MAX_TEMP',
    FILTER_RESET: 'FILTER_RESET',
})