export const types = Object.freeze({
    // Sync
    DAYS_START_FETCHING: 'DAYS_START_FETCHING',
    DAYS_STOP_FETCHING: 'DAYS_STOP_FETCHING',
    DAYS_SET_FETCHING_ERROR: 'DAYS_SET_FETCHING_ERROR',
    DAYS_FILL: 'DAYS_FILL',
    DAYS_DISPLAYED_DAY: 'DAYS_DISPLAYED_DAY',
    DAYS_SET_FILTERED_DATA: 'DAYS_SET_FILTERED_DATA',
    
    // Async
    DAYS_FETCH_ASYNC: 'DAYS_FETCH_ASYNC',
});